# Generated by Django 3.1.7 on 2021-03-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_users_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 10,00,000.00.'}}, help_text='Maximum 10,00,000.00', max_digits=9, verbose_name='Discount price'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 10,00,000.00.'}}, help_text='Maximum 10,00,000.00', max_digits=9, verbose_name='Regular price'),
        ),
    ]
