# Generated by Django 3.1.7 on 2021-04-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210326_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='address',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='address'),
        ),
    ]
