# Generated by Django 3.1.7 on 2021-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_animal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
