# Generated by Django 3.1.7 on 2021-04-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210418_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='please select', max_length=2),
        ),
    ]
