# Generated by Django 3.1.7 on 2021-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210418_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.IntegerField(default='NA', max_length=12),
        ),
    ]
