# Generated by Django 3.1.7 on 2021-04-18 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210418_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.IntegerField(default='NA', validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)]),
        ),
    ]
