# Generated by Django 3.1.7 on 2021-04-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210418_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
